<a href="https://colab.research.google.com/github/ayushpaliwal1920/Deep_Learning/blob/main/08_backpropagation_regression_demo2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
import numpy as np
import pandas as pd


In [68]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns = ['cgpa','profile_score','lpa'])

In [69]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [70]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [71]:
model = Sequential()

model.add(Dense(2,activation = 'linear',input_dim = 2))
model.add(Dense(1,activation = 'linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [72]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [73]:
model.get_weights()

[array([[ 0.3397659 ,  0.7240833 ],
        [-0.94030464,  0.00801229]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[1.3701714 ],
        [0.55325127]], dtype=float32),
 array([0.], dtype=float32)]

In [74]:
new_weights = [np.array([[0.1,  0.1  ],
        [0.1 , 0.1 ]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1],
        [0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [75]:
model.set_weights(new_weights)

In [76]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [77]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [78]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 27.8898 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 27.5677 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.2572 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 26.8885
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26.5678
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.1942 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25.8248
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25.4681
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25.0768
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24.6291 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24.2192 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.8162 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 23.3919
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 22.9542
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 22.4637
Epoch 16/75
4/4 ━

In [79]:
model.get_weights()

[array([[0.3737034 , 0.3737034 ],
        [0.36562183, 0.36562183]], dtype=float32),
 array([0.27238038, 0.27238038], dtype=float32),
 array([[0.37297437],
        [0.37297437]], dtype=float32),
 array([0.20484132], dtype=float32)]